---
name: "demo_db__rakam_test"
version: "1.0.0"
profile: "default"
source-paths:
- "models"
analysis-paths:
- "analysis"
target-path: "target"
models:
  segment:
    vars:
      segment_page_views_table: "\"DEMO_DB\".\"DEMO\".\"PAGES\""
      segment_sessionization_trailing_window: 3
      segment_inactivity_cutoff: "30 * 60"
      segment_pass_through_columns: []
